export default [
  "United States",
  "Canada",
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and/or Barbuda",
  "Argentina", "Armenia",
  "Aruba", "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana", "Bouvet Island",
  "Brazil", "British Indian Ocean Territory",
  "Brunei Darussalam", "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad", "Chile", "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia", "Comoros",
  "Congo", "Cook Islands",
  "Costa Rica", "Croatia (Hrvatska)",
  "Cuba", "Cyprus", "Czech Republic",
  "Denmark", "Djibouti", "Dominica",
  "Dominican Republic", "East Timor",
  "Ecudaor", "Egypt", "El Salvador",
  "Equatorial Guinea", "Eritrea", "Estonia",
  "Ethiopia", "Falkland Islands (Malvinas)",
  "Faroe Islands"
]
